name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 1: Set up Node.js for frontend and backend
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Step 2: Install dependencies for frontend and backend
    - name: Install dependencies (Frontend)
      run: |
        cd frontend
        npm install

    - name: Install dependencies (Backend)
      run: |
        cd backend
        npm install

    # Step 3: Run security audit for backend (using npm audit)
    - name: Security Audit (Backend)
      run: |
        cd backend
        npm audit --audit-level=high  # Only show vulnerabilities with high level

    # Step 4: Run security audit for frontend (using npm audit)
    - name: Security Audit (Frontend)
      run: |
        cd frontend
        npm audit --audit-level=high  # Only show vulnerabilities with high level

    # Step 5: Build frontend and backend (if no security vulnerabilities are found)
    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Build backend
      run: |
        cd backend
        npm run build

    # (Optional) You can add deployment steps here
    # Step 6: Deploy to AWS (or other platform)
    # - name: Deploy to AWS
    #   run: ... (Your deployment steps)
